--!A cross-platform build utility based on Lua
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Copyright (C) 2015-present, Xmake Open Source Community.
--
-- @author      ruki
-- @file        setmetatable.lua
--

-- the native lua `setmetatable`
--
-- it is not in the sandbox by default: a module which builds objects with metatables is
-- a module which is hard to serialize and to cache, and xmake passes plain tables
-- around on purpose. it is here for the code which really wants operator overloading or
-- an `__index` fallback
--
-- @note the same in lua 5.1 and 5.4
--
-- e.g.
--
-- import("lib.lua.setmetatable")
--
-- local obj = setmetatable({}, {__index = function (tbl, key) return "?" end})
--
return setmetatable
